### ISSUE TITLE
Latest v2.1.11 version fails to run

### ISSUE THREAD

**Issue by tomjn** [veracode/veracode-sca#28]
After upgrading form 2.1.10 to 2.1.11 the action fails to run with this output:

```
Run veracode/veracode-sca@v2.1.11
Start command
curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan . --quick  
Scan finished with exit code:  0
Store json Results as Artifact
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
/home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:1915
            throw new Error(`File ${file} does not exist`);
                  ^

Error: File scaResults.txt does not exist
    at getUploadSpecification (/home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:1915:19)
    at DefaultArtifactClient.<anonymous> (/home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:88:91)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:58:71
    at new Promise (<anonymous>)
    at __webpack_modules__.9157.__awaiter (/home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:54:12)
    at DefaultArtifactClient.uploadArtifact (/home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:83:[16](https://github.com/hm-sc/standard-chartered-nr/actions/runs/8143707108/job/22256146353#step:4:17))
    at /home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:38651:63
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/veracode/veracode-sca/v2.1.11/dist/index.js:38498:71
```

**Comment by raizen-renatofilizzola** [comment]
same here.

Back to 2.1.10, all fine.

**Comment by julz0815** [comment]
this is already solved
