### ISSUE TITLE
Support monorepo project

### ISSUE THREAD

**Issue by af732p** [veracode/veracode-sca#32]
The results upload artifact name is defined hard coded as "Veracode Agent Based SCA Results"
In case of Monorepo project, each sub project is scanned separately.
The uploaded artifact name must be defined differently for each sub project otherwise the upload override each other or fail the job.
The requirement is to add additional input for setting the Upload Artifact name.

**Comment by amorrow-flexion** [comment]
the problem persists with srcclr.ts line 122. We cannot have a hard coded artifact name 'VeraCode Agent Based SCA Results'. We need a name based on a parameter

**Comment by julz0815** [comment]
@af732p & @amorrow-flexion can you try version "artifactname" of this action?

This version adds a parameter called "artifactname" to the action. This string will be appended to the artifact name if set on the action run.

```
jobs:
  veracode-sca-task1:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@artifactname
        with:
          create-issues: true
          debug: true
          artifactname: scan1

  veracode-sca-task2:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@artifactname
        with:
          create-issues: true
          debug: true
          artifactname: scan2

  veracode-sca-task3:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@artifactname
        with:
          create-issues: true
          debug: true
          artifactname: scan3
```

![Image](https://github.com/user-attachments/assets/632c2980-8e15-4e3d-b7d7-b3db42be7f23)

**Comment by governmentSponsored** [comment]
@julz0815 we attempted that and unfortunately do not get those different artifact names. See [changes in these two files](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/compare/CAMS-514-reenable-veracode-sca-scans-on-all-commits?expand=1)

We made sure to match the following from that comment:
•	Parameter – artifactname 
•	Version used – artifactname
•	Added debug to help troubleshoot

Doesn’t seem to matter what we do, it stays at that same artifact name

![Image](https://github.com/user-attachments/assets/78d77957-3005-44c6-94fe-02129b1c987d)

**Comment by governmentSponsored** [comment]
Hey @julz0815 no worries! Unfortunately, we have different errors now related to pulling down files it needs to run the action. I can re-run with debug on, but it's a little too verbose. See logs below for the errors we're encountering now.

```
Start command
curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan user-interface  
Command to run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan user-interface  
Error: stderr: Feb 07, 2025 5:20:17 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeBeginning
INFO: [client #1 @770cae59] opening connection to (unknown):443

Error: stderr: Feb 07, 2025 5:20:18 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeComplete
INFO: [client #1 @770cae59] established connection with (unknown):443

Error: stderr: Feb 07, 2025 5:20:18 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyConnectionClosed
INFO: [client #1 @770cae59] disconnected from (unknown):443

Error: stderr: Feb 07, 2025 5:20:27 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeBeginning
INFO: [client #2 @1eabfad5] opening connection to (unknown):443

Error: stderr: Feb 07, 2025 5:20:27 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeComplete
INFO: [client #2 @1eabfad5] established connection with (unknown):443

Error: stderr: Feb 07, 2025 5:20:30 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyConnectionClosed
INFO: [client #2 @1eabfad5] disconnected from (unknown):443

Error: stderr: Feb 07, 2025 5:20:30 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeBeginning
INFO: [client #3 @43cf5bff] opening connection to (unknown):443

Error: stderr: Feb 07, 2025 5:20:30 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeComplete
INFO: [client #3 @43cf5bff] established connection with (unknown):443

Error: stderr: Feb 07, 2025 5:20:31 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyConnectionClosed
INFO: [client #3 @43cf5bff] disconnected from (unknown):443

Scan finished with exit code:  0
Veracode SCA agent scanning engine ready
Running the NPM scanner
npm warn config only Use `--omit=dev` to omit dev dependencies from the install.
npm error code ELSPROBLEMS
npm error invalid: @cams/common@ /home/runner/work/Bankruptcy-Oversight-Support-Systems/Bankruptcy-Oversight-Support-Systems/user-interface/node_modules/@cams/common
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-02-07T17_20_26_728Z-debug-0.log
Scanning completed
Found 446 lines of code
Processing results...
Processing results complete
Summary Report
Scan ID                                        432925d8-6414-4a39-a7bf-586da58b8582
Scan Date & Time                               Feb 07 2025 05:20PM UTC
Account type                                   ENTERPRISE
Scan engine                                    3.8.88 (latest 3.8.7)
Analysis time                                  12 seconds
User                                           runner
Project                                        /home/runner/work/Bankruptcy-Oversight-Support-Systems/Bankruptcy-Oversight-Support-Systems/user-interface
Package Manager(s)                             NPM
Open-Source Libraries
Total Libraries                                90
Direct Libraries                               15
Transitive Libraries                           81
Vulnerable Libraries                           0
Third Party Code                               99.9%
Security
With Vulnerable Methods                        0
Critical Risk Vulnerabilities                  0
High Risk Vulnerabilities                      0
Medium Risk Vulnerabilities                    0
Low Risk Vulnerabilities                       0
Licenses
Unique Library Licenses                        9
Libraries Using GPL                            0
Libraries With High Risk License               0
Libraries With Medium Risk License             1
Libraries With Low Risk License                93
Libraries With Multiple Licenses               4
Libraries With Unassessable License            0
Libraries With Unrecognizable License          0
Issues
Issue ID    Issue Type          Severity    Description                                                Library Name & Version In Use
412693      Outdated Library    3.0         Latest version at scan: 17.3.6-nightly.2502-04             @microsoft/applicationinsights-react-js 17.3.4
412694      Outdated Library    3.0         Latest version at scan: 3.3.6-nightly3.2502-04             @microsoft/applicationinsights-web 3.3.4
412695      Outdated Library    3.0         Latest version at scan: 22.13.1                            @types/node 22.12.0
412696      Outdated Library    3.0         Latest version at scan: [19](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/13204122440/job/36865216134#step:3:20).0.3                             @types/react-dom 18.3.5
412697      Outdated Library    3.0         Latest version at scan: 19.0.8                             @types/react 18.3.18
412698      Outdated Library    3.0         Latest version at scan: 3.2.4                              dompurify 3.2.3
412699      Outdated Library    3.0         Latest version at scan: 3.6.1                              launchdarkly-react-client-sdk 3.6.0
412700      Outdated Library    3.0         Latest version at scan: 19.1.0-canary-42687267-[20](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/13204122440/job/36865216134#step:3:21)250108    react-dom 18.3.1
412701      Outdated Library    3.0         Latest version at scan: 7.1.5                              react-router-dom 6.28.2
414102      Outdated Library    3.0         Latest version at scan: 19.1.0-canary-42687267-20250108    react 18.3.1
Full Report Details                            https://sca.analysiscenter.veracode.us/teams/D77HnN/scans/314960
The file has been saved!
Store json Results as Artifact
Artifact name is valid!
Root directory input is valid!
/home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:3705
            throw new Error(`File ${file} does not exist`);
                  ^
Error: File scaResults.json does not exist
    at getUploadZipSpecification (/home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:3705:19)
    at /home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:3562:91
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:3543:71
    at new Promise (<anonymous>)
    at __webpack_modules__.72[39](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/13204122440/job/36865216134#step:3:40)0.__awaiter (/home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:35[39](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/13204122440/job/36865216134#step:3:40):12)
    at uploadArtifact (/home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:3559:12)
    at DefaultArtifactClient.<anonymous> (/home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:2093:61)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/veracode/veracode-sca/artifactname/dist/index.js:2059:71
Node.js v20.18.0
```

**Comment by julz0815** [comment]
I'm even more confused now 🤔

I will check this, thy is for reporting!

**Comment by governmentSponsored** [comment]
@julz0815 I don't know if it helps at all, but we're connecting to the US Gov/FedRAMP environment. Not sure if that impacts interaction with sca action

**Comment by governmentSponsored** [comment]
Looks like there's another issue with a similar problem https://github.com/veracode/veracode-sca/issues/36

**Comment by julz0815** [comment]
@governmentSponsored could you send me your yml to review (jtotzekhallhuber@veracode.com) or is that maybe public anyway? 
Fed platform should not make any difference. 
What I have seen is that all artifact download and upload need to be on the same version 4 to work correctly.

**Comment by governmentSponsored** [comment]
@julz0815 the yaml is public, so you can view it here in the link that I posted earlier in this comment https://github.com/veracode/veracode-sca/issues/32#issuecomment-2643174770. 

Let me know if you need anything else

**Comment by julz0815** [comment]
this discussion was moved to a full support ticket. I will close the issue here.
